### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by mgmax** [manpaz/python-escpos#50]
Hi,

we are using escpos in a cashdesk application that will go open source soon. I noticed that your COPYING file states "GPL3", while escpos.py says "GPL", which would mean the antique GPL 1. As different license version cannot be mixed, this is a problem for us. Could you clarify this to say "GPL 3", or preferably "GPL3 or any later version"?

Thanks for your work,
Max

**Comment by manpaz** [comment]
Hi Max,

License version has been updated in all pertinent scripts.
Sorry about the confusion, and thank you for your contribution!

**Comment by patkan** [comment]
So the issue can be closed now, am I right?
