### ISSUE TITLE
can't initialize printer 

### ISSUE THREAD

**Issue by boshkash1151** [manpaz/python-escpos#51]
I get the error below when trying to initialize the printer with the vendor and product IDs

 
>>> from escpos import *
>>> epson = printer.Usb(0x0416,0x5011)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/escpos/printer.py", line 34, in __init__
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/escpos/printer.py", line 43, in open
    if self.device.is_kernel_driver_active(0):
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 721, in is_kernel_driver_active
    self._ctx.get_interface(self, interface).bInterfaceNumber)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 150, in get_interface
    cfg = self.get_active_configuration(device)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 165, in get_active_configuration
    bConfigurationValue=self.backend.get_configuration(self.handle)
  File "/usr/local/lib/python2.7/dist-packages/usb/util.py", line 176, in find_descriptor
    return _interop._next(desc_iter(k, v))
  File "/usr/local/lib/python2.7/dist-packages/usb/_interop.py", line 60, in _next
    return next(iter)
  File "/usr/local/lib/python2.7/dist-packages/usb/util.py", line 157, in desc_iter
    for d in desc:
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 742, in __iter__
    yield Configuration(self, i)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 418, in __init__
    configuration
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 711, in get_configuration_descriptor
    config, byref(cfg)))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 571, in _check
    raise USBError(_str_error[ret], ret, _libusb_errno[ret])
KeyError: -101

Thanks a lot

**Comment by piniyini** [comment]
Hello bosh

Can you check if the user you are using can execute these files?

`ls -l `

Also which printer is this, is this USB or Serial, does the printer support both or just one, if so which one?

Thanks

**Comment by boshkash1151** [comment]
I am running all the commands currently as sudo to avoid any issues with permissions


It is a USB printer. I got it from Amazon here is the link
http://www.amazon.com/Imagestore-Brainydeal-SC9-2012-High-speed-Receipt/dp/B005HH2YVY


Thanks piniyini

**Comment by piniyini** [comment]
Hi

When you connect the printer and type

`lsusb `

Does it show up on the list?

Thanks

**Comment by boshkash1151** [comment]
hi

Yes it shows the list. The printer is the fourth in the list below:

Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp.
Bus 001 Device 006: ID 0416:5011 Winbond Electronics Corp.



Thanks

**Comment by mentarus** [comment]
Did you follow "3. Define your printer" as per https://github.com/manpaz/python-escpos/blob/master/README ?

**Comment by boshkash1151** [comment]
mentarus,

I tried but when i initialize it as follows 
       Epson = escpos.Escpos(0x04b8,0x0202,0)
I get the following error:
TypeError: this constructor takes no arguments

**Comment by piniyini** [comment]
Take the zero i.e third parameter, out

Epson = escpos.Escpos(0x04b8,0x0202)

Any luck?

**Comment by piniyini** [comment]
I've just realised your first comment already shows 

`epson = printer.Usb(0x0416,0x5011)`

which means this is unlikely to work.

Also I read comment on the Amazon page from an "experienced linux user" who said they could not get this to work.

When I set up my epson it came with a linux driver, was there one included for this one?

**Comment by boshkash1151** [comment]
no it did not 

I installed CUPS which had the needed driver. I could print text using echo "hello world" > /dev/usb/lp0

Also most features are working when using escpos-php, but i need Python to integrate it with an already running app.

**Comment by piniyini** [comment]
Hello bosh

Would you be kind enough to link to the escpos php page? I'd like to take a
look.

Thanks

**Comment by manpaz** [comment]
Hi boshkash1151,

If you can print using /dev/usb/lp0, then you can define your printer as
```python
epson = printer.File()
```
The default file is /dev/usb/lp0, but this also give you the chance to use any other device file if the printer is created on /dev with another name, ie: /dev/usb/lp1 or /dev/lp0. So assuming, you assuming that your printer is on lp1, then you can initialize the printer with
```python
epson = printer.File("/dev/usb/lp1")
```
This should be in the wiki, but for some reason I missed it, so I'm updating it right away.

Thank you!

**Comment by boshkash1151** [comment]
piniyini,
sorry for not adding the link here it is: https://github.com/mike42/escpos-php


manpaz,
Thanks for the advice, I will try it and get back to you

**Comment by boshkash1151** [comment]
thanks manpaz

It works now using printer.File("/dev/usb/lp1")

one more issue when i try to print images it either prints garbage or black box 

Thanks

**Comment by piniyini** [comment]
Hello Bosh

Have you tried with a PNG image? Also you might have to install some image
libraries before it starts to print.

Thanks

**Comment by boshkash1151** [comment]
yes i tried .png and .gif and they were both small images. I attached them below. 

Also what are the libraries needed. There is no exception produced that i could trace

![tux](https://cloud.githubusercontent.com/assets/13046762/8463076/485c8d5c-2038-11e5-98e8-2c749f1da5e5.gif)

![tux](https://cloud.githubusercontent.com/assets/13046762/8463077/486291e8-2038-11e5-9a28-6cdbc3930342.png)

**Comment by piniyini** [comment]
Try these commands and see if it helps, it worked for me on my Epson

```
$ sudo apt-get install python-pip
$ sudo apt-get install python-dev libjpeg-dev libfreetype6-dev zlib1g-dev
```

also to note make sure the images have a white background and not a transparent one

**Comment by piniyini** [comment]
"one more issue when i try to print images it either prints garbage or black box"

what kind of image format prints the black box? this happened to me too and all i had to do was make it a white background

**Comment by piniyini** [comment]
also, did you manage to print an image via escpos-php?

**Comment by boshkash1151** [comment]
Thanks piniyini 

>Try these commands and see if it helps, it worked for me on my Epson

>$ sudo apt-get install python-pip
>$ sudo apt-get install python-dev libjpeg-dev libfreetype6-dev zlib1g-dev
>also to note make sure the images have a white background and not a transparent one


I installed the packages and tried a jpg image. Only the first image is printed correctly, but whenever i try to print a second image it prints it as garbage. I would need to turn the printer on then off to print the image 

To print images one after another I should split them with something (e.g. epson.text("\n"))

>what kind of image format prints the black box? this happened to me too and all i had to do was make >it a white background

It was a png with transparent background

>also, did you manage to print an image via escpos-php?

yes there is method called bitImage which prints all of the images

**Comment by piniyini** [comment]
I think I will buy this aswell just to have a tinker around, anything major I should be concerned about, printing speed? Max length/size of images? Anything?

Thanks

**Comment by boshkash1151** [comment]
The issues i found so far

1) Images needs to be separated by an empty line if you are using python escpos. 
2) Images in python-escpos have a limit of height of 255px this constraint does not exist if you use php-escpos. 
3) I can't print barcodes
4) I can print QR codes only using python-escpos 
5) I have problem with printing non-latin words such as Thai, Arabic

These are the issues i have found so far, but all have workarounds.

**Comment by piniyini** [comment]
There is a fix for #2, which I use myself ... I cant find it right now but I'll send it over tonight or you can search for it as it was written by someone and they posted the link in one of the issues here.

Thanks for the insight, I will give it a test drive myself.

Cheers bosh

**Comment by piniyini** [comment]
One last thing (hopefully), does the php cut command work with this printer?

**Comment by boshkash1151** [comment]
unfortunately i was not able to test it. I think my printer does not have this capability to confirm if it really working or not. 
I cut the paper manually

**Comment by manpaz** [comment]
Thank you @boshkash1151 sh1151 for your reply.
Think the main issue has been solved as you can initialize the printer, so I'll be closing this ticket.

Additionally, I've committed a new code to deal with transparent images.
Please go ahead and check if that helps with any other issue.

I'm aware that you have some other issues as well for this particular model, so, do you mind to check if it is related to some other open tickets please? if not, feel free to open a ticket for that particular type of printer and I'll do my best to help.

Thank you!
