### ISSUE TITLE
"printer" not defined

### ISSUE THREAD

**Issue by taylorstevens** [manpaz/python-escpos#63]
I haven't been able to get the example working. I followed the instructions on the Raspberry Pi wiki, I'm in the python-escpos/escpos directory, and my code is as follows (exactly what's on the front page):

#!/usr/bin/env python
from escpos import *

Epson = printer.Usb(0x04b8,0x0202)
...
Epson.cut

Is there anything I'm doing wrong? I've re-installed the package twice, making sure to use sudo both times, as well as the other dependencies. Any help would be greatly appreciated. Thank you!

**Comment by taylorstevens** [comment]
Apparently I should not have been in the escpos directory. And I had to run it with sudo. But I'm printing!

**Comment by manpaz** [comment]
Good to know :+1:
